"""empty message

Revision ID: 9732b79690
Revises: None
Create Date: 2015-09-10 18:32:20.034457

"""

# revision identifiers, used by Alembic.
revision = '9732b79690'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyramid')
    op.add_column('imgpaths', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_imgpaths_timestamp'), 'imgpaths', ['timestamp'], unique=False)
    op.drop_index('ix_imgpaths_timesharp', table_name='imgpaths')
    op.drop_column('imgpaths', 'timesharp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imgpaths', sa.Column('timesharp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_imgpaths_timesharp', 'imgpaths', ['timesharp'], unique=False)
    op.drop_index(op.f('ix_imgpaths_timestamp'), table_name='imgpaths')
    op.drop_column('imgpaths', 'timestamp')
    op.create_table('pyramid',
    sa.Column('IdImg', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('NameImg', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('DataImg', mysql.LONGBLOB(), nullable=False),
    sa.PrimaryKeyConstraint('IdImg'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
